"use client";

import { Landmark, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function PaymentInformationPage() {
  const [profile, setProfile] = useState<{ licenseNumber: string; licenseExpiration?: string; payoutAccountHolderName?: string; payoutAccountType?: string; payoutRoutingLast4?: string; payoutAccountLast4?: string }>({ licenseNumber: "" });
  const [saved, setSaved] = useState(false);
  useEffect(() => { fetch("/api/anesthesiologists/onboarding").then((response) => response.json()).then((data) => setProfile(data.profile ?? { licenseNumber: "" })); }, []);

  return <div className="max-w-3xl space-y-6"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-800">Clinical portal</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Licenses and payment information</h1><p className="mt-1 text-sm text-slate-500">Keep your service eligibility and payout details current.</p></div><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-teal-800" size={22} /><div><h2 className="font-bold text-slate-900">Professional licenses</h2><p className="mt-1 text-sm text-slate-500">License information comes from your onboarding record.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-slate-400">Primary license number</p><p className="mt-1 font-medium text-slate-800">{profile.licenseNumber || "Not provided"}</p></div><div><p className="text-xs font-semibold uppercase text-slate-400">License expiration</p><p className="mt-1 font-medium text-slate-800">{profile.licenseExpiration ? new Date(profile.licenseExpiration).toLocaleDateString() : "Not provided"}</p></div></div><Link href="/anesthesiologists/workspace/onboarding" className="mt-5 inline-block text-sm font-semibold text-teal-800">Update onboarding information</Link></section><section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-start gap-3"><Landmark className="mt-0.5 text-teal-800" size={22} /><div><h2 className="font-bold text-slate-900">Payout account</h2><p className="mt-1 text-sm text-slate-500">Only masked payout details are displayed after onboarding.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2 text-sm"><p><span className="font-semibold text-slate-500">Account holder:</span> {profile.payoutAccountHolderName || "Not provided"}</p><p><span className="font-semibold text-slate-500">Account type:</span> {profile.payoutAccountType || "Not provided"}</p><p><span className="font-semibold text-slate-500">Routing:</span> {profile.payoutRoutingLast4 ? `•••• ${profile.payoutRoutingLast4}` : "Not provided"}</p><p><span className="font-semibold text-slate-500">Account:</span> {profile.payoutAccountLast4 ? `•••• ${profile.payoutAccountLast4}` : "Not provided"}</p></div></section>{saved ? <p className="text-sm font-semibold text-teal-800">Saved</p> : null}</div>;
}
