"use client";

import { FileText, Upload } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

export default function PatientDocumentsPage() {
  const [uploaded, setUploaded] = useState<string[]>(["Medication list.pdf"]);
  return <main className="w-full max-w-none p-0"><section className="mx-auto max-w-5xl px-5 py-8 sm:px-8 lg:px-10"><Link href="/patients/portal" className="text-xs font-semibold text-teal-800 hover:text-teal-950">Back to your pre-op plan</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_0.8fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Documents</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Records and instructions</h1><p className="mt-2 text-sm text-slate-500">Keep your care team informed with current records and review your preoperative instructions.</p><label className="mt-7 flex cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-teal-200 bg-teal-50/50 p-8 text-center hover:bg-teal-50"><Upload className="text-teal-800" size={25} /><span className="mt-3 text-sm font-semibold text-teal-900">Upload a document</span><span className="mt-1 text-xs text-slate-500">Medication lists, test results, and outside records</span><input type="file" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) setUploaded((items) => [...items, file.name]); }} /></label><div className="mt-5 rounded-lg border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-900">Your uploaded documents</h2><div className="mt-3 divide-y divide-slate-100">{uploaded.map((file) => <div key={file} className="flex items-center gap-3 py-3"><FileText size={18} className="text-teal-800" /><span className="flex-1 text-sm font-medium text-slate-700">{file}</span><span className="text-xs font-semibold text-teal-800">Received</span></div>)}</div></div></div><aside className="h-fit rounded-lg border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-teal-800">Personalized instructions</p><h2 className="mt-2 text-lg font-bold text-slate-900">Before surgery</h2><ul className="mt-5 space-y-4 text-sm leading-6 text-slate-600"><li>Hold oral hypoglycemic medication on the morning of surgery unless your care team instructs otherwise.</li><li>Continue beta blockers with a sip of water.</li><li>Follow the fasting instructions provided by your surgical facility.</li><li>Bring an updated medication list on your surgery day.</li></ul></aside></div></section></main>;
}
