import { differenceInCalendarDays, format } from "date-fns";
import { getCurrentUser } from "@/lib/current-user";
import { getInstitutionReferrals } from "@/lib/institution-dashboard";
import { computeClearance } from "@/lib/institution-data";

function dayLabel(date: Date) { const diff = differenceInCalendarDays(date, new Date()); return diff === 0 ? "Today" : diff === 1 ? "Tomorrow" : format(date, "EEEE, MMM d"); }

export default async function SchedulePage() {
  const user = await getCurrentUser();
  const referrals = (await getInstitutionReferrals(user?.surgeryCenterId)).filter((referral) => referral.surgeryDate.getTime() >= new Date().setHours(0, 0, 0, 0) && referral.surgeryDate.getTime() <= Date.now() + 30 * 86400000);
  const groups = new Map<string, typeof referrals>();
  referrals.forEach((referral) => { const key = format(referral.surgeryDate, "yyyy-MM-dd"); groups.set(key, [...(groups.get(key) ?? []), referral]); });
  return <div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-teal-800">Surgery Center</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Schedule</h1><p className="mt-1 text-sm text-slate-500">Upcoming procedures for your facility, with clearance status visible before the OR date.</p></div><div className="space-y-4">{Array.from(groups.entries()).map(([key, cases]) => <div key={key} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-3"><h2 className="text-base font-bold text-slate-900">{dayLabel(cases[0].surgeryDate)}</h2><span className="text-xs font-medium text-slate-500">{cases.length} case{cases.length > 1 ? "s" : ""} · {cases.filter((item) => computeClearance(item).status !== "met").length} awaiting clearance</span></div><div className="mt-3 divide-y divide-slate-100">{cases.map((referral) => { const clearance = computeClearance(referral); return <div key={referral.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold text-slate-900">{referral.patient}</p><p className="text-xs text-slate-500">{referral.procedure} · {referral.surgeon}</p></div><div className="flex items-center gap-3"><span className="text-xs font-medium text-slate-600">{referral.stage.replaceAll("_", " ")}</span><span className={`rounded-full border px-2.5 py-0.5 text-[11px] font-semibold ${clearance.status === "overdue" ? "bg-red-50 text-red-700 border-red-100" : clearance.status === "met" ? "bg-emerald-50 text-emerald-700 border-emerald-100" : "bg-slate-100 text-slate-700 border-slate-200"}`}>{clearance.label}</span></div></div>; })}</div></div>)}{groups.size === 0 ? <p className="rounded-xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-500">No procedures scheduled in the next 30 days.</p> : null}</div></div>;
}
