import Link from "next/link";

export const metadata = {
  title: "About Us | GetPreOp",
  description: "Learn about GetPreOp's mission, vision, and leadership in virtual anesthesiology-led preoperative optimization.",
};

export default function AboutPage() {
  return <main className="w-full max-w-none p-0">
    <section className="relative overflow-hidden bg-slate-950 text-white"><img src="https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1800&q=85" alt="Anesthesiologist meeting with a patient before surgery" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-slate-950/65" /><div className="relative mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><p className="text-xs font-bold uppercase tracking-[0.18em] text-teal-300">About GetPreOp</p><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight tracking-tight sm:text-6xl">The most important work in surgery often happens before the patient enters the building.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">GetPreOp brings rigor, continuity, and human attention to the preoperative window, so preparation is not left to chance.</p></div></section>
    <section className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-[0.75fr_1.25fr] lg:items-center lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Founded in clinical experience</p><p className="mt-4 text-2xl font-bold leading-8 text-slate-950">Know the patient before the patient arrives for surgery.</p><div className="mt-7 max-w-md overflow-hidden rounded-lg bg-slate-100"><img src="/dr-jessica-onwudiwe.jpg" alt="Dr. Jessica C. Onwudiwe, MD" className="aspect-[4/3] w-full object-cover object-center" /><div className="bg-slate-50 px-4 py-4"><p className="font-bold text-slate-900">Dr. Jessica C. Onwudiwe, MD</p><p className="mt-1 text-sm text-slate-500">Founder, GetPreOp</p></div></div></div><div className="space-y-5 text-base leading-7 text-slate-600"><p>GetPreOp was founded by Dr. Jessica C. Onwudiwe, MD, a U.S. board-certified anesthesiologist who saw firsthand that some of surgery&apos;s biggest challenges do not begin in the operating room. They begin well before the day of surgery.</p><p>After graduating from the University of Missouri-Kansas City and completing a rigorous four-year anesthesiology residency at the University of Chicago, Dr. Onwudiwe saw what proactive preoperative care can change: a more complete clinical picture, fewer unanswered questions, and time for a team to act.</p><p>A careful pre-op evaluation can clarify medications, identify anesthesia risk, retrieve missing records or testing, and give patients the guidance they need. In too many settings, that work remains fragmented, rushed, or difficult to navigate. GetPreOp exists to close that gap.</p></div></div></section>
    <section className="border-y border-slate-200 bg-slate-50 py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Our clinical standard</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Better preparation depends on better clinical judgment.</h2><p className="mt-4 text-base leading-7 text-slate-600">We are committed to the highest standards of care. GetPreOp prioritizes anesthesiologists who received dedicated preoperative clinic training during residency, bringing first-hand experience in the details that shape a patient&apos;s readiness for surgery.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-sm font-bold text-teal-800">01</p><h3 className="mt-4 text-lg font-bold text-slate-900">Pre-op trained clinicians</h3><p className="mt-2 text-sm leading-6 text-slate-600">Our model prioritizes anesthesiologists with residency-based pre-op clinic experience.</p></article><article className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-sm font-bold text-teal-800">02</p><h3 className="mt-4 text-lg font-bold text-slate-900">Patient-first preparation</h3><p className="mt-2 text-sm leading-6 text-slate-600">Every assessment is designed to reduce uncertainty and make next steps understandable.</p></article><article className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-sm font-bold text-teal-800">03</p><h3 className="mt-4 text-lg font-bold text-slate-900">Accountable delivery</h3><p className="mt-2 text-sm leading-6 text-slate-600">Clear reports and visible tasks help care teams act while time still matters.</p></article></div></div></section>
    <section className="bg-white py-16"><div className="mx-auto grid max-w-7xl gap-5 px-5 sm:grid-cols-2 sm:px-8 lg:px-10"><article className="rounded-lg bg-teal-800 p-8 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-100">Mission</p><h2 className="mt-4 text-2xl font-bold">Make every patient more prepared for surgery.</h2><p className="mt-4 text-sm leading-7 text-teal-50">We deliver accessible, anesthesiology-led assessments that reveal risk early and give every care team a practical readiness plan.</p></article><article className="rounded-lg border border-slate-200 bg-slate-50 p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Vision</p><h2 className="mt-4 text-2xl font-bold text-slate-950">A surgical system with fewer preventable surprises.</h2><p className="mt-4 text-sm leading-7 text-slate-600">We envision preoperative care that is timely, complete, compassionate, and integrated into every patient&apos;s path to surgery.</p></article></div></section>
    <section className="bg-teal-800 py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:flex sm:items-end sm:justify-between sm:gap-8 sm:px-8 lg:px-10"><div className="max-w-2xl"><h2 className="text-3xl font-bold tracking-tight">A more prepared patient is a better starting point for care.</h2><p className="mt-3 text-sm leading-6 text-teal-50">See how GetPreOp supports safer, more coordinated surgical readiness.</p></div><Link href="/how-we-partner/institutions" className="mt-6 inline-block rounded-lg bg-white px-5 py-3 text-sm font-semibold text-teal-900 hover:bg-teal-50 sm:mt-0">Explore partnership</Link></div></section>
  </main>;
}
