import Link from "next/link";
import { RolePicker } from "@/components/role-picker";

const outcomes = [
  ["Assess before surgery day", "Digital intake, records, and anesthesia review bring risk forward."],
  ["Assign the right next step", "Readiness status makes optimization and specialist needs visible."],
  ["Give every team a clear report", "A concise clinical plan arrives when the care team can still act."],
];

export default function Home() {
  return <main className="w-full max-w-none p-0">
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.03fr_0.97fr] lg:px-10 lg:py-20"><div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Anesthesia-led preoperative readiness</p><h1 className="mt-4 max-w-2xl text-4xl font-bold leading-tight tracking-tight text-slate-950 sm:text-5xl">A more prepared path to every procedure.</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">GetPreOp unites surgical facilities, credentialed anesthesiologists, and patients around the work that determines readiness before surgery day.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/institutions" className="rounded-lg bg-teal-800 px-5 py-3 text-sm font-semibold text-white transition hover:bg-teal-900">For surgical facilities</Link><Link href="/anesthesiologists" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50">For anesthesiologists</Link></div><p className="mt-5 text-xs text-slate-500">Structured intake. Anesthesia-led assessment. Clear readiness reporting.</p></div><div className="relative overflow-hidden rounded-lg bg-slate-900 shadow-sm"><img src="https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1400&q=85" alt="Surgical care team preparing together" className="h-full min-h-[400px] w-full object-cover opacity-85" /><div className="absolute bottom-5 left-5 right-5 rounded-lg border border-white/20 bg-slate-950/85 p-5 text-white backdrop-blur-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-300">Readiness, made visible</p><p className="mt-2 text-lg font-bold">One coordinated workflow from referral to report delivery.</p></div></div></div></section>
    <section className="bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-8 sm:grid-cols-3 sm:px-8 lg:px-10"><div><p className="text-2xl font-bold">24-48h</p><p className="mt-1 text-sm text-slate-300">target report delivery window</p></div><div><p className="text-2xl font-bold">State-matched</p><p className="mt-1 text-sm text-slate-300">credentialed clinician routing</p></div><div><p className="text-2xl font-bold">One source</p><p className="mt-1 text-sm text-slate-300">of truth for every case</p></div></div></section>
    <section className="bg-slate-50 py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">A stronger pre-op operating model</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Turn scattered tasks into an accountable readiness plan.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{outcomes.map(([title, description], index) => <article key={title} className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-sm font-bold text-teal-800">0{index + 1}</p><h3 className="mt-4 text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></div></section>
    <section className="border-y border-slate-200 bg-white py-16"><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">What the platform connects</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">Built for the handoffs that decide whether a case proceeds.</h2><Link href="/what-we-offer" className="mt-6 inline-block text-sm font-semibold text-teal-800 hover:text-teal-950">Explore platform capabilities</Link></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-lg border border-slate-200 p-5"><h3 className="font-bold text-slate-900">Facilities</h3><p className="mt-2 text-sm leading-6 text-slate-600">Refer cases, track clearance deadlines, and keep your surgical schedule informed.</p></article><article className="rounded-lg border border-slate-200 p-5"><h3 className="font-bold text-slate-900">Anesthesiologists</h3><p className="mt-2 text-sm leading-6 text-slate-600">Accept eligible cases in licensed states with transparent state-specific compensation.</p></article><article className="rounded-lg border border-slate-200 p-5"><h3 className="font-bold text-slate-900">Patients</h3><p className="mt-2 text-sm leading-6 text-slate-600">Complete intake and receive practical instructions before their procedure.</p></article><article className="rounded-lg border border-slate-200 p-5"><h3 className="font-bold text-slate-900">Care teams</h3><p className="mt-2 text-sm leading-6 text-slate-600">Receive a clear report that supports appropriate next steps and safer scheduling.</p></article></div></div></section>
    <section className="bg-teal-800 py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:flex sm:items-end sm:justify-between sm:gap-8 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-100">Start with your role</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Ready to make pre-op readiness easier to run?</h2><p className="mt-3 text-sm leading-6 text-teal-50">Join GetPreOp to bring early assessment, clinical accountability, and clearer communication to every scheduled case.</p></div><Link href="/signup" className="mt-6 inline-block shrink-0 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-teal-900 transition hover:bg-teal-50 sm:mt-0">Create an account</Link></div></section>
    <div className="mx-auto max-w-7xl px-5 py-12 sm:px-8 lg:px-10"><RolePicker /></div>
  </main>;
}
