import Link from "next/link";

const domains = [
  { id: "biomedical-engineering", number: "01", title: "Biomedical Engineering", tags: "Materials science · biomechanics · biomaterials", description: "Designing at the intersection of biology, mechanics, and human health." },
  { id: "cancer-research", number: "02", title: "Cancer Research", tags: "Breast cancer · brain cancer · tumor microenvironment", description: "Researching the physical and biological conditions that shape disease." },
  { id: "diagnostics", number: "03", title: "Diagnostics", tags: "Mechanical biomarkers · cancer detection · medical imaging", description: "Turning complex signals into earlier, more actionable clinical insight." },
  { id: "ai-samd", number: "04", title: "AI & SaMD", tags: "AI-enabled cancer detection · regulatory pathways · healthcare AI", description: "Moving intelligent tools from promising models toward responsible use." },
  { id: "medical-technology", number: "05", title: "Medical Technology", tags: "Medical devices · DICOM · imaging workflows · digital health", description: "Building technology that can work inside real clinical environments." },
  { id: "regulated-healthcare", number: "06", title: "Regulated Healthcare", tags: "Pharmaceutical manufacturing · CQV · validation · quality", description: "Executing carefully where quality, compliance, and patient safety matter." },
  { id: "program-leadership", number: "07", title: "Technical Program Leadership", tags: "$10M+ programs · engineering · contractors · stakeholders · risk", description: "Aligning technical teams, decisions, budgets, and delivery under pressure." },
  { id: "consulting", number: "08", title: "Consulting", tags: "Healthcare technology · regulatory strategy · product development", description: "Helping ambitious teams turn uncertainty into a path they can execute." },
  { id: "product-building", number: "09", title: "Product Building", tags: "MedSecOp · patient workflows · physician workflows · imaging", description: "Creating practical systems for the people who deliver and receive care." },
];

export default function Home() {
  return <main className="w-full max-w-none p-0">
    <section className="border-b border-slate-200 bg-[#f4f1eb]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-12 sm:px-8 lg:grid-cols-[1fr_0.72fr] lg:items-center lg:px-10 lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Independent researcher · builder · operator</p><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[0.98] tracking-tight text-slate-950 sm:text-7xl">Science. Technology. Healthcare. Execution.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">I work across biomedical research, cancer diagnostics, healthcare technology, regulated product development and technical program leadership - turning complex problems into research, products and programs.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#work" className="rounded-lg bg-teal-800 px-5 py-3 text-sm font-semibold text-white transition hover:bg-teal-900">Explore my work</a><a href="#collaborate" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:bg-white">Collaborate with me</a><a href="mailto:contact@getpreop.com?subject=Work with Killian" className="rounded-lg border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700 transition hover:bg-white">Work with me</a></div><a href="mailto:contact@getpreop.com?subject=Résumé request" className="mt-5 inline-block text-sm font-semibold text-teal-800 underline decoration-teal-200 underline-offset-4 hover:text-teal-950">Download résumé</a></div><div className="relative"><div className="absolute -inset-3 rounded-lg bg-teal-900/10" /><div className="relative overflow-hidden rounded-lg bg-slate-200"><img src="/dr-jessica-onwudiwe.jpg" alt="Killian Chukwuebuka, PhD" className="aspect-[4/5] w-full object-cover object-top grayscale-[15%]" /></div><div className="relative -mt-10 ml-5 mr-5 rounded-lg bg-slate-950 p-5 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-300">A portfolio in motion</p><p className="mt-2 text-base font-semibold leading-6">Research depth. Product judgment. Delivery discipline.</p></div></div></div></section>
    <section id="work" className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">The index</p><h2 className="mt-4 text-4xl font-bold tracking-tight">What I&apos;ve worked across</h2><p className="mt-4 text-base leading-7 text-slate-300">A career shaped by problems that refuse to stay inside one category. Select a domain to see the kind of work, questions, and outcomes it contains.</p></div><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-slate-700 bg-slate-700 md:grid-cols-2 lg:grid-cols-3">{domains.map((domain) => <a key={domain.id} href={`#${domain.id}`} className="group bg-slate-950 p-6 transition hover:bg-teal-900"><span className="text-xs font-bold text-teal-300">{domain.number}</span><h3 className="mt-8 text-xl font-bold">{domain.title}</h3><p className="mt-3 text-sm leading-6 text-slate-300 group-hover:text-teal-50">{domain.tags}</p><span className="mt-6 block text-xs font-bold uppercase tracking-wider text-teal-300">View focus &darr;</span></a>)}</div></div></section>
    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Selected focus</p><h2 className="mt-3 text-4xl font-bold tracking-tight text-slate-950">Where the work gets specific.</h2></div><p className="max-w-md text-sm leading-6 text-slate-600">Each area below is a doorway into a body of work - from scientific questions to regulated execution and products in use.</p></div><div className="mt-10 space-y-0">{domains.map((domain, index) => <article id={domain.id} key={domain.id} className="scroll-mt-24 grid gap-5 border-t border-slate-200 py-8 md:grid-cols-[90px_0.8fr_1.2fr] md:items-start"><p className="text-sm font-bold text-teal-800">{domain.number}</p><h3 className="text-2xl font-bold text-slate-950">{domain.title}</h3><div><p className="text-sm font-semibold leading-6 text-teal-900">{domain.tags}</p><p className="mt-3 max-w-xl text-sm leading-7 text-slate-600">{domain.description} The work brings together disciplined investigation, practical communication, and a bias toward outcomes that can survive contact with the real world.</p><a href="#work" className="mt-4 inline-block text-xs font-bold uppercase tracking-wider text-slate-500 hover:text-teal-800">Back to index &uarr;</a></div></article>)}</div></div></section>
    <section id="collaborate" className="bg-[#f4f1eb] py-16"><div className="mx-auto grid max-w-7xl gap-8 px-5 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Conversation & discovery</p><h2 className="mt-3 text-4xl font-bold tracking-tight text-slate-950">The best work starts with a hard problem.</h2></div><div><p className="text-lg leading-8 text-slate-700">I collaborate with researchers, healthcare organizations, product teams, and operators who need to move from complexity to clarity - then from clarity to execution.</p><div className="mt-7 flex flex-wrap gap-3"><a href="mailto:contact@getpreop.com?subject=Collaboration inquiry" className="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800">Start a conversation</a><a href="mailto:contact@getpreop.com?subject=Résumé request" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-white">Request résumé</a></div></div></div></section>
    <section className="border-t border-slate-200 bg-slate-950 py-8 text-slate-300"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-4 px-5 text-sm sm:px-8 lg:px-10"><span className="font-semibold text-white">Killian Chukwuebuka, PhD</span><span>Research · Products · Programs</span></div></section>
  </main>;
}
