"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { InstitutionDashboardCase } from "@/lib/institution-dashboard";

const riskLabels = { SPECIALIST: "Specialist", OPTIMIZE: "Optimize", READY: "Ready" };

export function InstitutionDashboardContent({ facilityName, cases }: { facilityName: string; cases: InstitutionDashboardCase[] }) {
  const [urgency, setUrgency] = useState("all");
  const [risk, setRisk] = useState("all");
  const [window, setWindow] = useState("14");
  const now = Date.now();
  const filtered = useMemo(() => cases.filter((item) => {
    const deadline = new Date(item.clearanceDeadline).getTime();
    const daysToSurgery = (new Date(item.surgeryDate).getTime() - now) / 86400000;
    const matchesUrgency = urgency === "all" || (urgency === "urgent" && (deadline < now || daysToSurgery <= 2)) || (urgency === "waiting" && item.stage === "INTAKE_PENDING");
    const matchesRisk = risk === "all" || item.risk === risk;
    const matchesWindow = window === "all" || (daysToSurgery >= 0 && daysToSurgery <= Number(window));
    return matchesUrgency && matchesRisk && matchesWindow;
  }), [cases, now, urgency, risk, window]);
  const urgent = cases.filter((item) => new Date(item.clearanceDeadline).getTime() < now || (new Date(item.surgeryDate).getTime() - now) / 86400000 <= 2).sort((a, b) => new Date(a.clearanceDeadline).getTime() - new Date(b.clearanceDeadline).getTime());
  const assessed = cases.filter((item) => item.risk);
  const ready = assessed.filter((item) => item.risk === "READY").length;
  const active = cases.filter((item) => !["CLEARED", "REPORT_DELIVERED"].includes(item.stage));
  const formatDate = (value: string) => new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });

  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-teal-800">{facilityName}</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Today&apos;s readiness view</h1><p className="mt-1 text-sm text-slate-500">The cases that need attention first, followed by your upcoming surgical schedule.</p></div><Link href="/surgery-centers/dashboard/referrals/new" className="rounded-lg bg-teal-800 px-4 py-2 text-xs font-semibold text-white hover:bg-teal-900">New referral</Link></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Active cases" value={active.length} hint="Not yet cleared" /><Metric label="Needs attention" value={urgent.length} hint="Due soon or overdue" tone="red" /><Metric label="Ready for surgery" value={assessed.length ? `${Math.round((ready / assessed.length) * 100)}%` : "0%"} hint={`${ready} of ${assessed.length} assessed`} tone="green" /><Metric label="Awaiting intake" value={cases.filter((item) => item.stage === "INTAKE_PENDING").length} hint="Patient action needed" tone="amber" /></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-bold text-slate-900">Priority queue</h2><p className="mt-1 text-xs text-slate-500">Start here each day. Filters keep the list focused.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Filter urgency" value={urgency} onChange={(e) => setUrgency(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs"><option value="all">All urgency</option><option value="urgent">Due soon / overdue</option><option value="waiting">Awaiting intake</option></select><select aria-label="Filter risk" value={risk} onChange={(e) => setRisk(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs"><option value="all">All risk</option><option value="SPECIALIST">Specialist</option><option value="OPTIMIZE">Optimize</option><option value="READY">Ready</option></select><select aria-label="Filter surgery window" value={window} onChange={(e) => setWindow(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs"><option value="14">Next 14 days</option><option value="30">Next 30 days</option><option value="all">All dates</option></select></div></div><div className="mt-4 divide-y divide-slate-100">{filtered.length ? filtered.slice(0, 8).map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold text-slate-900">{item.patient}</p><p className="text-xs text-slate-500">{item.procedure} · {formatDate(item.surgeryDate)} · {item.surgeon}</p></div><div className="flex items-center gap-2 text-[11px] font-semibold"><span className={`rounded-full px-2.5 py-1 ${item.risk === "SPECIALIST" ? "bg-red-50 text-red-700" : item.risk === "OPTIMIZE" ? "bg-amber-50 text-amber-800" : item.risk === "READY" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{item.risk ? riskLabels[item.risk] : "Awaiting intake"}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600">{item.stage.replaceAll("_", " ")}</span></div></div>) : <p className="py-8 text-center text-sm text-slate-500">No cases match these filters.</p>}</div></section>
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-base font-bold text-slate-900">Next action</h2><p className="mt-1 text-xs text-slate-500">The single most useful thing to do next.</p>{urgent[0] ? <div className="mt-4 rounded-lg border border-red-100 bg-red-50 p-4"><p className="text-sm font-bold text-slate-900">{urgent[0].patient}</p><p className="mt-1 text-xs text-red-700">{urgent[0].procedure} · surgery {formatDate(urgent[0].surgeryDate)}</p><p className="mt-3 text-xs font-medium text-red-700">Review readiness and resolve the clearance blocker before the procedure date.</p><Link href="/surgery-centers/dashboard/readiness-board" className="mt-3 inline-block text-xs font-bold text-red-800">Open readiness board →</Link></div> : <p className="mt-4 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">No urgent cases. Your queue is currently on track.</p>}</section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-base font-bold text-slate-900">Workflow shortcuts</h2><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link href="/surgery-centers/dashboard/referrals" className="rounded-lg border border-slate-200 p-3 text-sm font-semibold text-slate-700 hover:border-teal-300">Review referrals</Link><Link href="/surgery-centers/dashboard/schedule" className="rounded-lg border border-slate-200 p-3 text-sm font-semibold text-slate-700 hover:border-teal-300">View schedule</Link><Link href="/surgery-centers/dashboard/readiness-board" className="rounded-lg border border-slate-200 p-3 text-sm font-semibold text-slate-700 hover:border-teal-300">Open readiness board</Link><Link href="/surgery-centers/dashboard/cancellations" className="rounded-lg border border-slate-200 p-3 text-sm font-semibold text-slate-700 hover:border-teal-300">Review cancellations</Link></div></section></div>
  </div>;
}

function Metric({ label, value, hint, tone = "default" }: { label: string; value: string | number; hint: string; tone?: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 text-3xl font-bold ${tone === "red" ? "text-red-600" : tone === "green" ? "text-emerald-600" : tone === "amber" ? "text-amber-600" : "text-slate-900"}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></article>; }