import Link from "next/link";

const careerStages = [
  ["Materials Engineering", "Material behavior, interfaces, and the foundations of engineered systems."],
  ["Biomedical Engineering", "Applying engineering methods to biological questions and human health."],
  ["Cancer Research", "Investigating how disease changes cells, tissues, and their environment."],
  ["Cancer Biomechanics", "Mechanical characterization of cancer cells and tumor behavior."],
  ["Mechanical Biomarkers", "Exploring mechanical signatures that may support cancer detection."],
  ["Diagnostic Research", "Translating measurable biology into clinically meaningful insight."],
  ["Healthcare Consulting", "Helping teams navigate product, regulatory, and technical decisions."],
  ["AI / SaMD", "Advisory work around AI-enabled cancer detection and regulatory pathways."],
  ["Medical Imaging", "DICOM, imaging workflows, and the infrastructure around clinical review."],
  ["Digital Health", "Designing better patient, physician, and healthcare operations workflows."],
  ["Regulated Manufacturing", "$10M+ clean utilities and radiopharmaceutical manufacturing programs."],
  ["Technical Program Leadership", "Aligning engineering, quality, contractors, stakeholders, and risk."],
] as const;

const selectedWork = [
  { number: "01", title: "Mechanical Biomarkers for Cancer Detection", label: "Biomedical Engineering · Cancer Research · Diagnostics", question: "Can mechanical behavior reveal a measurable signature of cancer?", work: "Cell mechanics · viscoelasticity · creep · cytoskeletal structure · AFM · statistical analysis", outcome: "Research investigating mechanical properties as potential biomarkers for distinguishing malignant and non-malignant cells.", href: "#cancer-mechanics" },
  { number: "02", title: "Engineering the infrastructure behind radiopharmaceutical manufacturing", label: "Technical Program Management · Pharmaceutical Manufacturing · CQV", question: "How do you coordinate the infrastructure a highly regulated manufacturing program depends on?", work: "Clean utilities · engineering · QA · CQV · manufacturing · contractors · supply chain", outcome: "Managed and coordinated major clean-utilities projects supporting a new radiopharmaceutical manufacturing program.", href: "#regulated-manufacturing" },
  { number: "03", title: "AI and the future of cancer detection", label: "AI Healthcare · SaMD · Regulatory Strategy", question: "What must be considered when an AI product enters a high-consequence clinical workflow?", work: "AI · clinical problem · product · regulation · validation", outcome: "Advisory work involving partners developing AI-enabled breast cancer detection solutions and exploring regulatory pathways and considerations for AI/SaMD.", href: "#ai-samd" },
  { number: "04", title: "MedSecOp", label: "Product Strategy · Medical Imaging · Digital Health", question: "How can patients, imaging, and clinical expertise connect more naturally?", work: "Patient → Imaging → DICOM → Secure Platform → Physician → Expert Review → Patient", outcome: "Building a digital bridge between patient workflows, medical imaging, physician workflows, and expert review.", href: "https://github.com/Killianchuks/getpreop" },
];

const researchPillars = [
  ["01", "Cancer Mechanics", "Viscoelasticity · creep · cellular mechanics · cytoskeleton · mechanical heterogeneity · breast cancer · triple-negative breast cancer", "#cancer-mechanics"],
  ["02", "Brain Cancer", "Glioblastoma · single-cell mechanics · viscoelastic properties · brain microenvironment · brain metastasis", "#brain-cancer"],
  ["03", "Tumor Microenvironment", "Mechanical stress · immune escape · mechanical/metabolic interactions · tumor microenvironment", "#tumor-microenvironment"],
  ["04", "Biomaterials & Cancer Treatment", "Magnetite nanoparticles · PDMS · PLGA/PCL · drug delivery · doxorubicin · hyperthermia · photothermal treatment", "#biomaterials"],
] as const;

export function PortfolioHome() {
  return <main className="w-full max-w-none p-0">
    <section className="border-b border-slate-200 bg-[#f4f1eb]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 sm:px-8 lg:grid-cols-[1.08fr_0.92fr] lg:items-center lg:px-10 lg:py-24"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Killian Onwudiwe, PhD</p><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-[0.96] tracking-tight text-slate-950 sm:text-7xl">Science. Technology. Healthcare. Execution.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">I work across biomedical research, cancer diagnostics, healthcare technology, regulated product development and technical program leadership - turning complex problems into research, products and programs.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#work" className="rounded-lg bg-teal-800 px-5 py-3 text-sm font-semibold text-white hover:bg-teal-900">Explore my work</a><a href="#collaborate" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-white">Collaborate with me</a><a href="mailto:contact@getpreop.com?subject=Work with Killian Onwudiwe" className="rounded-lg border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-white">Work with me</a></div><a href="mailto:contact@getpreop.com?subject=Résumé request" className="mt-5 inline-block text-sm font-semibold text-teal-800 underline decoration-teal-200 underline-offset-4">Download résumé</a></div><div className="relative min-h-[380px] overflow-hidden rounded-lg bg-slate-950 p-7 text-white"><div className="absolute right-[-20%] top-[-20%] h-72 w-72 rounded-full border border-teal-500/30" /><div className="absolute bottom-[-25%] left-[-15%] h-80 w-80 rounded-full border border-amber-300/20" /><div className="relative flex h-full min-h-[325px] flex-col justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">A career in motion</p><p className="mt-5 max-w-xs text-3xl font-bold leading-tight">From cells and materials to products and programs.</p></div><div className="grid grid-cols-2 gap-3 text-xs text-slate-300"><div className="border-l-2 border-teal-500 pl-3">Research<br /><span className="text-white">Biology · mechanics</span></div><div className="border-l-2 border-amber-300 pl-3">Execution<br /><span className="text-white">Products · programs</span></div></div></div></div></div></section>
    <section id="work" className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">The breadth</p><h2 className="mt-4 text-4xl font-bold tracking-tight">What I&apos;ve worked across</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-300">Select a domain to reveal the kind of questions, tools, and outcomes inside the work.</p><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-slate-700 bg-slate-700 md:grid-cols-2 lg:grid-cols-3">{careerStages.map(([title, description], index) => <details key={title} className="group bg-slate-950 p-5 open:bg-teal-900"><summary className="cursor-pointer list-none"><span className="text-xs font-bold text-teal-300">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{description}</p><span className="mt-4 block text-xs font-bold uppercase tracking-wider text-teal-300">Click to explore +</span></summary><p className="mt-5 border-t border-white/20 pt-4 text-sm leading-6 text-teal-50">This stage builds on the one before it, connecting technical depth with increasingly applied healthcare problems.</p></details>)}</div></div></section>
    <section className="bg-white py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Career at a glance</p><h2 className="mt-3 text-4xl font-bold tracking-tight text-slate-950">A career across disciplines</h2><p className="mt-4 max-w-2xl text-lg font-semibold leading-8 text-slate-700">The breadth is not random. Each stage builds on the previous one.</p><div className="mt-9 flex gap-3 overflow-x-auto pb-5">{careerStages.map(([title], index) => <a key={title} href={`#career-${index}`} className="group min-w-[170px] border-t-2 border-teal-700 pt-4"><span className="text-xs font-bold text-teal-800">{String(index + 1).padStart(2, "0")}</span><span className="mt-2 block text-sm font-bold text-slate-900 group-hover:text-teal-800">{title}</span>{index < careerStages.length - 1 ? <span className="mt-4 block text-xs text-slate-400">↓</span> : null}</a>)}</div><div className="mt-5 grid gap-3 md:grid-cols-3">{careerStages.map(([title, description], index) => <article id={`career-${index}`} key={`detail-${title}`} className="scroll-mt-24 rounded-lg bg-slate-50 p-5"><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></article>)}</div></div></section>
    <section id="work" className="border-y border-slate-200 bg-[#f4f1eb] py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Selected work</p><h2 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight text-slate-950">Work that spans the laboratory, the product and the real world.</h2><div className="mt-10 grid gap-5 lg:grid-cols-2">{selectedWork.map((project) => <article key={project.number} className="flex flex-col rounded-lg border border-slate-200 bg-white p-6"><div className="flex items-start justify-between gap-4"><span className="text-xs font-bold text-teal-800">PROJECT {project.number}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-500">{project.label}</span></div><h3 className="mt-7 text-2xl font-bold leading-tight text-slate-950">{project.title}</h3><div className="mt-6 space-y-4 text-sm leading-6 text-slate-600"><p><strong className="text-slate-900">Question</strong><br />{project.question}</p><p><strong className="text-slate-900">Work</strong><br />{project.work}</p><p><strong className="text-slate-900">Outcome</strong><br />{project.outcome}</p></div><a href={project.href} className="mt-7 text-sm font-bold text-teal-800 hover:text-teal-950">{project.number === "04" ? "Explore MedSecOp ↗" : "Explore work →"}</a></article>)}</div></div></section>
    <section id="research" className="bg-slate-950 py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">Research</p><h2 className="mt-3 text-4xl font-bold tracking-tight">Years spent investigating how disease changes biology at the cellular, mechanical and material levels.</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{researchPillars.map(([number, title, tags, href]) => <a key={number} href={href} className="rounded-lg border border-slate-700 bg-slate-900 p-6 transition hover:border-teal-400 hover:bg-teal-900"><span className="text-sm font-bold text-teal-300">{number}</span><h3 className="mt-5 text-2xl font-bold">{title}</h3><p className="mt-4 text-sm leading-7 text-slate-300">{tags}</p><span className="mt-6 block text-xs font-bold uppercase tracking-wider text-teal-300">Read research story →</span></a>)}</div><div className="mt-10 space-y-5 border-t border-slate-700 pt-8"><ResearchStory id="cancer-mechanics" title="Cancer Mechanics" question="How do the mechanical properties of cancer cells differ, and can those differences be measured?" approach="Mechanical characterization, viscoelasticity, creep behavior, cytoskeletal structure, and statistical analysis." finding="Research focused on mechanical heterogeneity across cancer cell populations and its potential value as a measurable biological signal." /><ResearchStory id="brain-cancer" title="Brain Cancer" question="What can single-cell mechanics reveal about glioblastoma and the brain microenvironment?" approach="Investigation of single-cell mechanical and viscoelastic properties in the context of glioblastoma and brain metastasis." finding="Work examining how cell mechanics interact with the environment surrounding brain cancer." /><ResearchStory id="tumor-microenvironment" title="Tumor Microenvironment" question="How do mechanical stress and metabolic conditions shape tumor behavior?" approach="Connecting mechanical stress, immune escape, and mechanical/metabolic interactions." finding="A systems view of the tumor microenvironment as an active participant in disease progression." /><ResearchStory id="biomaterials" title="Biomaterials & Cancer Treatment" question="How can engineered materials support targeted cancer treatment?" approach="Magnetite nanoparticles, PDMS, PLGA/PCL, drug delivery, doxorubicin, hyperthermia, and photothermal treatment." finding="Research exploring materials and treatment strategies that could improve how cancer is studied and treated." /></div></div></section>
    <section id="collaborate" className="bg-teal-800 py-16 text-white"><div className="mx-auto max-w-7xl px-5 sm:flex sm:items-end sm:justify-between sm:gap-8 sm:px-8 lg:px-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-100">Conversation & discovery</p><h2 className="mt-3 text-4xl font-bold tracking-tight">The best work starts with a hard problem.</h2><p className="mt-4 text-base leading-7 text-teal-50">I collaborate with researchers, healthcare organizations, product teams, and operators who need to move from complexity to clarity, then from clarity to execution.</p></div><a href="mailto:contact@getpreop.com?subject=Collaborate with Killian Onwudiwe" className="mt-7 inline-block shrink-0 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-teal-900 hover:bg-teal-50 sm:mt-0">Start a conversation</a></div></section>
  </main>;
}

function ResearchStory({ id, title, question, approach, finding }: { id: string; title: string; question: string; approach: string; finding: string }) {
  return <article id={id} className="scroll-mt-24 border-t border-slate-700 py-8"><h3 className="text-2xl font-bold text-white">{title}</h3><div className="mt-5 grid gap-5 md:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-300">The question</p><p className="mt-2 text-sm leading-6 text-slate-300">{question}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-teal-300">The approach</p><p className="mt-2 text-sm leading-6 text-slate-300">{approach}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-teal-300">The finding</p><p className="mt-2 text-sm leading-6 text-slate-300">{finding}</p></div></div><div className="mt-5 rounded-lg bg-white/10 p-4"><p className="text-xs font-bold uppercase tracking-wider text-teal-200">Why it matters</p><p className="mt-2 text-sm leading-6 text-slate-200">Making complex biology understandable creates better questions for diagnosis, treatment, and translation.</p></div></article>;
}
