"use client";

import { useState } from "react";

const chapters = [
  ["01", "Research", "I study how mechanics, materials, and biology interact to reveal new possibilities in cancer detection and treatment.", "#research"],
  ["02", "Translation", "I move ideas beyond the lab through diagnostics, medical imaging, AI/SaMD, and regulated healthcare strategy.", "#work"],
  ["03", "Execution", "I coordinate the technical, quality, and human systems that make ambitious healthcare programs real.", "#leadership"],
];

const work = [
  ["Mechanical biomarkers", "Cancer research · diagnostics", "Investigating whether the mechanical behavior of cells can become a measurable signal for distinguishing malignant and non-malignant states.", "Cell mechanics · viscoelasticity · creep · AFM · cytoskeletal structure"],
  ["Radiopharmaceutical infrastructure", "Program leadership · CQV", "Coordinating the clean utilities and delivery ecosystem behind a new radiopharmaceutical manufacturing program.", "$10M+ program · engineering · QA · CQV · contractors · supply chain"],
  ["AI and cancer detection", "AI healthcare · SaMD", "Advisory work with partners developing AI-enabled breast cancer detection solutions, including regulatory pathway considerations.", "AI · clinical problem · product · regulation · validation"],
  ["MedSecOp", "Product building · digital health", "Building a digital bridge between patients, medical imaging, DICOM workflows, physicians, and expert review.", "Patient → Imaging → DICOM → Platform → Physician → Review"],
];

const research = [
  ["Cancer mechanics", "Mechanical behavior is biology with another dimension. I investigate viscoelasticity, creep, cytoskeletal structure, and heterogeneity in breast cancer, including triple-negative breast cancer, to ask whether physical behavior can add signal to cancer research.", "How does a cancer cell's mechanical state change what we can measure?"],
  ["Brain cancer", "Glioblastoma and brain metastasis present a different mechanical landscape. Work in this area examines single-cell mechanics, viscoelastic properties, and the relationship between cancer cells and the brain microenvironment.", "What can the mechanics of one cell tell us about the environment around it?"],
  ["Tumor microenvironment", "Tumors are not isolated populations of cells. Mechanical stress, immune escape, and metabolic interactions create a living system where forces and signals shape behavior together.", "How do physical forces and metabolism cooperate inside a tumor?"],
  ["Biomaterials and treatment", "Magnetite nanoparticles, PDMS, PLGA/PCL, drug delivery, doxorubicin, hyperthermia, and photothermal treatment connect materials engineering to therapeutic possibility.", "How can engineered materials help us study or treat cancer more precisely?"],
];

export function PortfolioHomeV2() {
  const [researchIndex, setResearchIndex] = useState(0);
  return <main className="portfolio-v2">
    <section className="v2-hero"><div className="v2-wrap v2-hero-grid"><div className="v2-hero-copy"><p className="v2-kicker">Killian Onwudiwe, PhD</p><h1>Curiosity<br /><span>with direction.</span></h1><p className="v2-lede">I work across biomedical research, cancer diagnostics, healthcare technology, regulated product development, and technical program leadership - turning complex problems into research, products, and programs.</p><div className="v2-actions"><a href="#work" className="v2-button v2-button-primary">Explore my work <b>↘</b></a><a href="#collaborate" className="v2-button v2-button-outline">Start a conversation <b>↗</b></a></div><a href="mailto:contact@getpreop.com?subject=Résumé request" className="v2-resume">Download résumé <span>↗</span></a></div><div className="v2-portrait"><div className="v2-portrait-glow" /><div className="v2-portrait-frame"><img src="/dr-jessica-onwudiwe.jpg" alt="Professional portrait" /></div><div className="v2-caption"><span>01</span><p>Researcher<br /><strong>Builder · operator</strong></p></div></div></div></section>
    <section className="v2-intro"><div className="v2-wrap"><p className="v2-kicker">A point of view</p><h2>Some problems need a laboratory.<br /><em>Some need a bridge.</em></h2><p className="v2-intro-copy">My work lives in the space between discovery and delivery. I care about the question, the evidence, the people affected by the outcome, and the discipline required to make progress hold up in the real world.</p></div></section>
    <section className="v2-chapters"><div className="v2-wrap"><div className="v2-section-head"><p className="v2-kicker">The throughline</p><h2>Three ways I make difficult work move.</h2></div><div className="v2-chapter-grid">{chapters.map(([number, title, copy, href]) => <a href={href} key={number} className="v2-chapter"><span>{number}</span><h3>{title}</h3><p>{copy}</p><b>Enter chapter ↗</b></a>)}</div></div></section>
    <section id="work" className="v2-work"><div className="v2-wrap"><div className="v2-section-head"><p className="v2-kicker">Selected work</p><h2>From the laboratory to the real world.</h2><p>Different settings. The same instinct: understand the system, find the leverage, deliver with care.</p></div><div className="v2-work-list">{work.map(([title, label, copy, tools], index) => <article className="v2-work-item" key={title}><span className="v2-work-number">0{index + 1}</span><div><p className="v2-label">{label}</p><h3>{title}</h3><p className="v2-work-copy">{copy}</p><p className="v2-tools">{tools}</p></div><span className="v2-arrow">↗</span></article>)}</div></div></section>
    <section id="research" className="v2-research"><div className="v2-wrap"><div className="v2-section-head"><p className="v2-kicker">Research</p><h2>Questions that became bodies of work.</h2><p>Years spent investigating how disease changes biology at the cellular, mechanical, and material levels.</p></div><div className="v2-research-grid"><div className="v2-research-nav">{research.map(([title], index) => <button type="button" key={title} onClick={() => setResearchIndex(index)} className={index === researchIndex ? "active" : ""}><span>0{index + 1}</span>{title}<b>↗</b></button>)}</div><article className="v2-research-story"><p className="v2-label">{research[researchIndex][0]}</p><h3>{research[researchIndex][2]}</h3><div><p className="v2-label">The work</p><p>{research[researchIndex][1]}</p></div><div className="v2-research-mark"><span /><span /><span /><i>question → evidence → possibility</i></div></article></div></div></section>
    <section id="leadership" className="v2-leadership"><div className="v2-wrap v2-leadership-grid"><div><p className="v2-kicker">The operating side</p><h2>Good ideas deserve good execution.</h2></div><div className="v2-leadership-copy"><p>Technical program leadership is where scientific ambition meets constraints: quality, timelines, contractors, risk, budgets, stakeholders, and the decisions that cannot wait.</p><div className="v2-ecosystem"><span>Engineering</span><span>Quality</span><span>CQV</span><span>Manufacturing</span><span>Clients</span><span>Patients</span></div></div></div></section>
    <section id="collaborate" className="v2-close"><div className="v2-wrap"><p className="v2-kicker">Next question</p><h2>What are you trying to make possible?</h2><p>Bring a research question, a product challenge, or a program that needs clearer direction.</p><a href="mailto:contact@getpreop.com?subject=Conversation with Killian Onwudiwe" className="v2-button v2-button-light">Let&apos;s talk <b>↗</b></a></div></section>
  </main>;
}
