import Link from "next/link";
import { PricingCalculator } from "@/components/pricing-calculator";

export const metadata = {
  title: "Pricing | GetPreOp",
  description: "Simple per-case pricing for surgical facilities with custom volume pricing for hospitals and high-volume systems.",
};

export default function PricingPage() {
  return <main className="w-full max-w-none p-0"><section className="bg-slate-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-300">Institution pricing</p><h1 className="mt-5 max-w-4xl text-5xl font-bold leading-tight tracking-tight sm:text-6xl">See what a more prepared schedule could be worth.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Start with transparent $350-per-case pricing, then use your own facility assumptions to estimate the revenue GetPreOp could help protect.</p></div></section><section className="bg-slate-50 py-16"><div className="mx-auto grid max-w-5xl gap-6 px-5 sm:px-8 lg:grid-cols-[1fr_1fr] lg:px-10"><article className="rounded-lg border-2 border-teal-700 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-800">Standard access</p><h2 className="mt-4 text-2xl font-bold text-slate-950">$350 per completed case</h2><p className="mt-4 text-sm leading-6 text-slate-600">No monthly commitment. Each completed preoperative assessment includes the digital workflow, clinician review, readiness report, and care-team communication.</p><Link href="/signup?role=SURGERY_CENTER&plan=per-case&billing=annual" className="mt-7 block rounded-lg bg-teal-800 px-4 py-3 text-center text-sm font-semibold text-white hover:bg-teal-900">Register your facility</Link></article><article className="rounded-lg border border-slate-200 bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">High volume</p><h2 className="mt-4 text-2xl font-bold text-slate-950">Custom bulk pricing</h2><p className="mt-4 text-sm leading-6 text-slate-600">Hospitals, health systems, and high-volume surgical networks can contact us to discuss volume, facility mix, integrations, and service levels.</p><a href="mailto:contact@getpreop.com?subject=Bulk pricing discussion" className="mt-7 block rounded-lg bg-slate-900 px-4 py-3 text-center text-sm font-semibold text-white hover:bg-slate-800">Discuss bulk pricing</a></article></div></section><PricingCalculator /></main>;
}
